version: '3.8'
services:
  db:
    image: custom-postgres-pgvector:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=vector"]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
